version: "3.7"

services:
  sfu:
    image: pionwebrtc/ion-sfu:latest
    build:
      dockerfile: ./docker/sfu.Dockerfile
      context: .
    volumes:
      - "./configs/docker/sfu.toml:/configs/sfu.toml"
    ports:
      - "5000-5200:5000-5200/udp"
    depends_on:
      - nats
      - etcd
    networks:
      - ionnet

  biz:
    image: pionwebrtc/ion-biz:latest
    build:
      dockerfile: ./docker/biz.Dockerfile
      context: .
    volumes:
      - "./configs/docker/biz.toml:/configs/biz.toml"
    ports:
      - 8443:8443
    networks:
      - ionnet
    depends_on:
      - nats
      - etcd

  islb:
    image: pionwebrtc/ion-islb:latest
    build:
      dockerfile: ./docker/islb.Dockerfile
      context: .
    volumes:
      - "./configs/docker/islb.toml:/configs/islb.toml"
    depends_on:
      - nats
      - etcd
      - redis
    networks:
      - ionnet

  avp:
    image: pionwebrtc/ion-avp:latest
    build:
      dockerfile: ./docker/avp.Dockerfile
      context: .
    volumes:
      - "./configs/docker/avp.toml:/configs/avp.toml"
      - "./:/out/"
    depends_on:
      - nats
      - etcd
    networks:
      - ionnet

  nats:
    image: nats
    ports:
      - 4223:4222
    networks:
      - ionnet

  etcd:
    image: gcr.io/etcd-development/etcd:v3.4.9
    entrypoint: "/usr/local/bin/etcd"
    command: "--listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://0.0.0.0:2379"
    ports:
      - 2389:2379
    networks:
      - ionnet

  redis:
    image: redis:5.0.9
    ports:
      - 6380:6379
    networks:
      - ionnet

networks:
  ionnet:
    external: true
    name: ionnet
    driver: bridge
