[global]
pprof = ":6061"

# data center id
dc = "dc1"

[log]
level = "info"

[etcd]
# ["ip:port", "ip:port"]
addrs = ["127.0.0.1:2389"]

[nats]
url = "nats://127.0.0.1:4223"

[redis]
addrs = [":6380"]
password = ""
db = 0
